version: 0.2

env:
  variables:
    BUCKET_NAME: niladri-selenium-reports-2026

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven dependencies
      - service docker start
      - mvn clean install -DskipTests

  pre_build:
    commands:
      - echo Starting Docker Selenium Grid
      - docker network create grid
      - docker run -d -p 4444:4444 --name selenium-hub --network grid selenium/hub:4.18.1
      - |
        for i in 1 2 3
        do
          docker run -d --network grid \
          -e SE_EVENT_BUS_HOST=selenium-hub \
          -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
          -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
          selenium/node-chrome:4.18.1
        done
      - sleep 30

  build:
    commands:
      - echo Running Selenium Tests in Grid Mode
      - mvn test

  post_build:
    commands:
      - echo Uploading Extent Reports to S3
      - aws s3 cp reports/ s3://$BUCKET_NAME/ --recursive

      - echo Saving execution history to DynamoDB
      - |
        aws dynamodb put-item \
        --table-name SeleniumExecutionHistory \
        --item '{
          "buildId": {"S": "'$CODEBUILD_BUILD_ID'"},
          "status": {"S": "'$CODEBUILD_BUILD_SUCCEEDING'"},
          "timestamp": {"S": "'$(date)'"},
          "region": {"S": "ap-south-1"}
        }'

artifacts:
  files:
    - '**/*'