version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Chrome
      - apt-get install -y chromium-browser
      - echo Building project
      - mvn clean install -DskipTests

  build:
    commands:
      - echo Running Tests
      - mvn test

artifacts:
  files:
    - '**/*'